index:
  settings:
    analysis:
      analyzer:
        default:  # Indexing analyzer: doesn't use custom synonyms
          type: custom
          tokenizer: standard
          filter: [standard, lowercase, stop, stemmer_override, stemmer_english]
          char_filter: [normalize_quotes, strip_quotes]
        query_default:
          type: custom
          tokenizer: standard
          filter: [standard, lowercase, synonym, stop, stemmer_override, stemmer_english]
          char_filter: [normalize_quotes, strip_quotes]
        shingled_query_analyzer:
          type: custom
          tokenizer: standard
          filter: [standard, lowercase, stop, stemmer_override, stemmer_english, filter_shingle]
        exact_match:
          type: custom
          tokenizer: keyword
          filter: [trim, lowercase]
          char_filter: [normalize_quotes]
        best_bet_stemmed_match:
          type: custom
          tokenizer: standard
          filter: [standard, lowercase, stemmer_override, stemmer_english]
          char_filter: [normalize_quotes, strip_quotes]
        spelling_analyzer:
          type: custom
          tokenizer: standard
          filter: [standard, lowercase, shingle]
          char_filter: [normalize_quotes, strip_quotes]
        string_for_sorting:
          type: custom
          tokenizer: keyword
          filter: [trim, lowercase]
          char_filter: [normalize_quotes, strip_quotes]

      char_filter:
        strip_quotes:
          type: "pattern_replace"
          pattern: "\'"
          replacement: ""

        normalize_quotes:
          type: "mapping"
          mappings:
            - "\u0091=>\u0027"
            - "\u0092=>\u0027"
            - "\u2018=>\u0027"
            - "\u2019=>\u0027"
            - "\uFF07=>\u0027"

      filter:
        stemmer_english:
          type: stemmer
          name: english
        filter_shingle:
          type: shingle
          max_shingle_size: 2
          min_shingle_size: 2
